### ISSUE TITLE
Compatiblity isssue : SR5 / Monk's Active Tile Triggers

### ISSUE THREAD

**Issue by DjamZee** [shadowfoundry/sr5#426] opened 2023-09-21 13:27 UTC
Quand ce module est actif, de même que pour les modules "Automated Evocation - Companion Manager" et "Warp Gate" Il devient impossible de réaliser des jet de dés. Plus d'anim _Dice so nice_ et surtout plus rien dans le chat, c'est un peu genant, surtout pour un module aussi utile que MATT ^^. 

Voila, si vous pouvez jeter un œil quand vous aurez le temps ca serait bien 😄
____________________________________________________________________________________________________________________________________
When this module is active, as with the "Automated Evocation - Companion Manager" and "Warp Gate" modules, it becomes impossible to make dice rolls. No more "Dice so nice" anims and nothing in the chat, which is a bit annoying, especially for a module as useful as MATT ^^.

Voila, if you could have a look when you have time, that would be great 😄

**Comment by deurk** [comment] 2023-09-22 12:39
Thanks for your report. Apparently, it seems like it would be caused by the Warp Gate module rather than MATT. Could you confirm this?

If that is confirmed, it will not be compatible with Warp Gate until they fix the issue opened here:
https://github.com/trioderegion/warpgate/issues/145

Awaiting on your confirmation regarding which plugin triggers the error.

**Comment by deurk** [comment] 2023-09-22 12:41
Re-reading again, it seems like you are saying all 3 modules are creating the issue?

**Comment by deurk** [comment] 2023-09-22 12:48
For reference: https://github.com/ironmonk88/monks-active-tiles/issues/601

**Comment by deurk** [comment] 2023-12-06 05:51
Fixed on MATT side

**Closed by deurk** 2023-12-06 05:51 UTC
Labels: waiting for
